# Generated by Django 3.2.4 on 2021-07-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210705_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaiBao',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
