# Generated by Django 3.2.4 on 2021-07-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0010_myuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvarta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('avarta', models.ImageField(upload_to='avarta')),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
