# Generated by Django 3.2.4 on 2021-07-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20210721_1233'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useravarta',
            table='UserAvarta',
        ),
    ]
